### ISSUE TITLE
Past Medical History ITEMIDs

### ISSUE THREAD

**Issue by lkiljanek** [MIT-LCP/mimic-iii-paper#22]
How the ITEMID 225811 and 225059 get into the database ? 
Who provides this info ?
Is it part of EMR ? that physicians add ?
Or is it a part of post processing of H&P ?
Or maybe nursing notes ?
This ITEMIDS are past medical history...

Also, the HEMO PD under the item IDs ITEMID 225811 and  ITEMID 225059 mean pt is End stage renal disease on hemodialysis ?
I'd assume ?

**Comment by alistairewj** [comment]
I removed your expire flag question as it was answered here: https://github.com/MIT-LCP/mimic-code/issues/163

Those ITEMIDs are from the MetaVision information system which is used by care providers to document patient data at the bedside. All of the data in these ITEMIDs would be documented at the bedside while the patient is in the ICU.
