### ISSUE TITLE
Expire flag ?

### ISSUE THREAD

**Issue by lkiljanek** [MIT-LCP/mimic-iii-paper#23]
When  ? how many years after 2013 ? 2014 ? 2012 ? has it been most recently updated ?
Is it updated now for all patients ?
How about the social security deaths, is it safe to assume they are all updated at least 3 years after the MIMIC III database data migration was closed ?

Another questions is, 
How the ITEMID 225811 and 225059 get into the database ? 
Who provides this info ?
Is it part of EMR ? that physicians add ?
Or is it a part of post processing of H&P ?
Or maybe nursing notes ?
This ITEMIDS are past medical history...

Also, the HEMO PD under the item IDs ITEMID 225811 and  ITEMID 225059 mean pt is End stage renal disease on hemodialysis ?
I'd assume ?

**Comment by tompollard** [comment]
This is a duplicate of https://github.com/MIT-LCP/mimic-code/issues/163, so I'll close this issue.
